[package]
name = "nottirb/oklab"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

include = ["src", "src/**", "default.project.json", "wally.toml", "LICENSE"]
exclude = ["**", "*/**"]

[dependencies]